// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IndexGetRangeRequest struct {
	Shard                string   `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Start                int64    `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexGetRangeRequest) Reset()         { *m = IndexGetRangeRequest{} }
func (m *IndexGetRangeRequest) String() string { return proto.CompactTextString(m) }
func (*IndexGetRangeRequest) ProtoMessage()    {}
func (*IndexGetRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{0}
}
func (m *IndexGetRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRangeRequest.Unmarshal(m, b)
}
func (m *IndexGetRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRangeRequest.Marshal(b, m, deterministic)
}
func (dst *IndexGetRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRangeRequest.Merge(dst, src)
}
func (m *IndexGetRangeRequest) XXX_Size() int {
	return xxx_messageInfo_IndexGetRangeRequest.Size(m)
}
func (m *IndexGetRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRangeRequest proto.InternalMessageInfo

func (m *IndexGetRangeRequest) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *IndexGetRangeRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *IndexGetRangeRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type IndexGetRangeResponse struct {
	// Types that are valid to be assigned to Msg:
	//	*IndexGetRangeResponse_Info_
	//	*IndexGetRangeResponse_Data_
	Msg                  isIndexGetRangeResponse_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *IndexGetRangeResponse) Reset()         { *m = IndexGetRangeResponse{} }
func (m *IndexGetRangeResponse) String() string { return proto.CompactTextString(m) }
func (*IndexGetRangeResponse) ProtoMessage()    {}
func (*IndexGetRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{1}
}
func (m *IndexGetRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRangeResponse.Unmarshal(m, b)
}
func (m *IndexGetRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRangeResponse.Marshal(b, m, deterministic)
}
func (dst *IndexGetRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRangeResponse.Merge(dst, src)
}
func (m *IndexGetRangeResponse) XXX_Size() int {
	return xxx_messageInfo_IndexGetRangeResponse.Size(m)
}
func (m *IndexGetRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRangeResponse proto.InternalMessageInfo

type isIndexGetRangeResponse_Msg interface {
	isIndexGetRangeResponse_Msg()
}

type IndexGetRangeResponse_Info_ struct {
	Info *IndexGetRangeResponse_Info `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type IndexGetRangeResponse_Data_ struct {
	Data *IndexGetRangeResponse_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*IndexGetRangeResponse_Info_) isIndexGetRangeResponse_Msg() {}

func (*IndexGetRangeResponse_Data_) isIndexGetRangeResponse_Msg() {}

func (m *IndexGetRangeResponse) GetMsg() isIndexGetRangeResponse_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *IndexGetRangeResponse) GetInfo() *IndexGetRangeResponse_Info {
	if x, ok := m.GetMsg().(*IndexGetRangeResponse_Info_); ok {
		return x.Info
	}
	return nil
}

func (m *IndexGetRangeResponse) GetData() *IndexGetRangeResponse_Data {
	if x, ok := m.GetMsg().(*IndexGetRangeResponse_Data_); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IndexGetRangeResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IndexGetRangeResponse_OneofMarshaler, _IndexGetRangeResponse_OneofUnmarshaler, _IndexGetRangeResponse_OneofSizer, []interface{}{
		(*IndexGetRangeResponse_Info_)(nil),
		(*IndexGetRangeResponse_Data_)(nil),
	}
}

func _IndexGetRangeResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IndexGetRangeResponse)
	// msg
	switch x := m.Msg.(type) {
	case *IndexGetRangeResponse_Info_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *IndexGetRangeResponse_Data_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IndexGetRangeResponse.Msg has unexpected type %T", x)
	}
	return nil
}

func _IndexGetRangeResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IndexGetRangeResponse)
	switch tag {
	case 1: // msg.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IndexGetRangeResponse_Info)
		err := b.DecodeMessage(msg)
		m.Msg = &IndexGetRangeResponse_Info_{msg}
		return true, err
	case 2: // msg.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IndexGetRangeResponse_Data)
		err := b.DecodeMessage(msg)
		m.Msg = &IndexGetRangeResponse_Data_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IndexGetRangeResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IndexGetRangeResponse)
	// msg
	switch x := m.Msg.(type) {
	case *IndexGetRangeResponse_Info_:
		s := proto.Size(x.Info)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *IndexGetRangeResponse_Data_:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IndexGetRangeResponse_Info struct {
	Header               *IndexResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Start                int64                `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64                `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IndexGetRangeResponse_Info) Reset()         { *m = IndexGetRangeResponse_Info{} }
func (m *IndexGetRangeResponse_Info) String() string { return proto.CompactTextString(m) }
func (*IndexGetRangeResponse_Info) ProtoMessage()    {}
func (*IndexGetRangeResponse_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{1, 0}
}
func (m *IndexGetRangeResponse_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRangeResponse_Info.Unmarshal(m, b)
}
func (m *IndexGetRangeResponse_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRangeResponse_Info.Marshal(b, m, deterministic)
}
func (dst *IndexGetRangeResponse_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRangeResponse_Info.Merge(dst, src)
}
func (m *IndexGetRangeResponse_Info) XXX_Size() int {
	return xxx_messageInfo_IndexGetRangeResponse_Info.Size(m)
}
func (m *IndexGetRangeResponse_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRangeResponse_Info.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRangeResponse_Info proto.InternalMessageInfo

func (m *IndexGetRangeResponse_Info) GetHeader() *IndexResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *IndexGetRangeResponse_Info) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *IndexGetRangeResponse_Info) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type IndexGetRangeResponse_Data struct {
	Slice                *IndexSlice `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IndexGetRangeResponse_Data) Reset()         { *m = IndexGetRangeResponse_Data{} }
func (m *IndexGetRangeResponse_Data) String() string { return proto.CompactTextString(m) }
func (*IndexGetRangeResponse_Data) ProtoMessage()    {}
func (*IndexGetRangeResponse_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{1, 1}
}
func (m *IndexGetRangeResponse_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexGetRangeResponse_Data.Unmarshal(m, b)
}
func (m *IndexGetRangeResponse_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexGetRangeResponse_Data.Marshal(b, m, deterministic)
}
func (dst *IndexGetRangeResponse_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexGetRangeResponse_Data.Merge(dst, src)
}
func (m *IndexGetRangeResponse_Data) XXX_Size() int {
	return xxx_messageInfo_IndexGetRangeResponse_Data.Size(m)
}
func (m *IndexGetRangeResponse_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexGetRangeResponse_Data.DiscardUnknown(m)
}

var xxx_messageInfo_IndexGetRangeResponse_Data proto.InternalMessageInfo

func (m *IndexGetRangeResponse_Data) GetSlice() *IndexSlice {
	if m != nil {
		return m.Slice
	}
	return nil
}

type IndexPutRangeRequest struct {
	// Types that are valid to be assigned to Msg:
	//	*IndexPutRangeRequest_Info_
	//	*IndexPutRangeRequest_Data_
	Msg                  isIndexPutRangeRequest_Msg `protobuf_oneof:"msg"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *IndexPutRangeRequest) Reset()         { *m = IndexPutRangeRequest{} }
func (m *IndexPutRangeRequest) String() string { return proto.CompactTextString(m) }
func (*IndexPutRangeRequest) ProtoMessage()    {}
func (*IndexPutRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{2}
}
func (m *IndexPutRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPutRangeRequest.Unmarshal(m, b)
}
func (m *IndexPutRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPutRangeRequest.Marshal(b, m, deterministic)
}
func (dst *IndexPutRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPutRangeRequest.Merge(dst, src)
}
func (m *IndexPutRangeRequest) XXX_Size() int {
	return xxx_messageInfo_IndexPutRangeRequest.Size(m)
}
func (m *IndexPutRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPutRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPutRangeRequest proto.InternalMessageInfo

type isIndexPutRangeRequest_Msg interface {
	isIndexPutRangeRequest_Msg()
}

type IndexPutRangeRequest_Info_ struct {
	Info *IndexPutRangeRequest_Info `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type IndexPutRangeRequest_Data_ struct {
	Data *IndexPutRangeRequest_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*IndexPutRangeRequest_Info_) isIndexPutRangeRequest_Msg() {}

func (*IndexPutRangeRequest_Data_) isIndexPutRangeRequest_Msg() {}

func (m *IndexPutRangeRequest) GetMsg() isIndexPutRangeRequest_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *IndexPutRangeRequest) GetInfo() *IndexPutRangeRequest_Info {
	if x, ok := m.GetMsg().(*IndexPutRangeRequest_Info_); ok {
		return x.Info
	}
	return nil
}

func (m *IndexPutRangeRequest) GetData() *IndexPutRangeRequest_Data {
	if x, ok := m.GetMsg().(*IndexPutRangeRequest_Data_); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IndexPutRangeRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IndexPutRangeRequest_OneofMarshaler, _IndexPutRangeRequest_OneofUnmarshaler, _IndexPutRangeRequest_OneofSizer, []interface{}{
		(*IndexPutRangeRequest_Info_)(nil),
		(*IndexPutRangeRequest_Data_)(nil),
	}
}

func _IndexPutRangeRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IndexPutRangeRequest)
	// msg
	switch x := m.Msg.(type) {
	case *IndexPutRangeRequest_Info_:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Info); err != nil {
			return err
		}
	case *IndexPutRangeRequest_Data_:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IndexPutRangeRequest.Msg has unexpected type %T", x)
	}
	return nil
}

func _IndexPutRangeRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IndexPutRangeRequest)
	switch tag {
	case 1: // msg.info
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IndexPutRangeRequest_Info)
		err := b.DecodeMessage(msg)
		m.Msg = &IndexPutRangeRequest_Info_{msg}
		return true, err
	case 2: // msg.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IndexPutRangeRequest_Data)
		err := b.DecodeMessage(msg)
		m.Msg = &IndexPutRangeRequest_Data_{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IndexPutRangeRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IndexPutRangeRequest)
	// msg
	switch x := m.Msg.(type) {
	case *IndexPutRangeRequest_Info_:
		s := proto.Size(x.Info)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *IndexPutRangeRequest_Data_:
		s := proto.Size(x.Data)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type IndexPutRangeRequest_Info struct {
	Shard                string   `protobuf:"bytes,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Revision             int64    `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Start                int64    `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexPutRangeRequest_Info) Reset()         { *m = IndexPutRangeRequest_Info{} }
func (m *IndexPutRangeRequest_Info) String() string { return proto.CompactTextString(m) }
func (*IndexPutRangeRequest_Info) ProtoMessage()    {}
func (*IndexPutRangeRequest_Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{2, 0}
}
func (m *IndexPutRangeRequest_Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPutRangeRequest_Info.Unmarshal(m, b)
}
func (m *IndexPutRangeRequest_Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPutRangeRequest_Info.Marshal(b, m, deterministic)
}
func (dst *IndexPutRangeRequest_Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPutRangeRequest_Info.Merge(dst, src)
}
func (m *IndexPutRangeRequest_Info) XXX_Size() int {
	return xxx_messageInfo_IndexPutRangeRequest_Info.Size(m)
}
func (m *IndexPutRangeRequest_Info) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPutRangeRequest_Info.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPutRangeRequest_Info proto.InternalMessageInfo

func (m *IndexPutRangeRequest_Info) GetShard() string {
	if m != nil {
		return m.Shard
	}
	return ""
}

func (m *IndexPutRangeRequest_Info) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *IndexPutRangeRequest_Info) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *IndexPutRangeRequest_Info) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

type IndexPutRangeRequest_Data struct {
	Slice                *IndexSlice `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *IndexPutRangeRequest_Data) Reset()         { *m = IndexPutRangeRequest_Data{} }
func (m *IndexPutRangeRequest_Data) String() string { return proto.CompactTextString(m) }
func (*IndexPutRangeRequest_Data) ProtoMessage()    {}
func (*IndexPutRangeRequest_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{2, 1}
}
func (m *IndexPutRangeRequest_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPutRangeRequest_Data.Unmarshal(m, b)
}
func (m *IndexPutRangeRequest_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPutRangeRequest_Data.Marshal(b, m, deterministic)
}
func (dst *IndexPutRangeRequest_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPutRangeRequest_Data.Merge(dst, src)
}
func (m *IndexPutRangeRequest_Data) XXX_Size() int {
	return xxx_messageInfo_IndexPutRangeRequest_Data.Size(m)
}
func (m *IndexPutRangeRequest_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPutRangeRequest_Data.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPutRangeRequest_Data proto.InternalMessageInfo

func (m *IndexPutRangeRequest_Data) GetSlice() *IndexSlice {
	if m != nil {
		return m.Slice
	}
	return nil
}

type IndexPutRangeResponse struct {
	Header               *IndexResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IndexPutRangeResponse) Reset()         { *m = IndexPutRangeResponse{} }
func (m *IndexPutRangeResponse) String() string { return proto.CompactTextString(m) }
func (*IndexPutRangeResponse) ProtoMessage()    {}
func (*IndexPutRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{3}
}
func (m *IndexPutRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexPutRangeResponse.Unmarshal(m, b)
}
func (m *IndexPutRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexPutRangeResponse.Marshal(b, m, deterministic)
}
func (dst *IndexPutRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexPutRangeResponse.Merge(dst, src)
}
func (m *IndexPutRangeResponse) XXX_Size() int {
	return xxx_messageInfo_IndexPutRangeResponse.Size(m)
}
func (m *IndexPutRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexPutRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IndexPutRangeResponse proto.InternalMessageInfo

func (m *IndexPutRangeResponse) GetHeader() *IndexResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type IndexShard struct {
	Revision             int64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Slices               []*IndexSliceLocation `protobuf:"bytes,2,rep,name=slices,proto3" json:"slices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IndexShard) Reset()         { *m = IndexShard{} }
func (m *IndexShard) String() string { return proto.CompactTextString(m) }
func (*IndexShard) ProtoMessage()    {}
func (*IndexShard) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{4}
}
func (m *IndexShard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexShard.Unmarshal(m, b)
}
func (m *IndexShard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexShard.Marshal(b, m, deterministic)
}
func (dst *IndexShard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexShard.Merge(dst, src)
}
func (m *IndexShard) XXX_Size() int {
	return xxx_messageInfo_IndexShard.Size(m)
}
func (m *IndexShard) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexShard.DiscardUnknown(m)
}

var xxx_messageInfo_IndexShard proto.InternalMessageInfo

func (m *IndexShard) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *IndexShard) GetSlices() []*IndexSliceLocation {
	if m != nil {
		return m.Slices
	}
	return nil
}

type IndexSliceLocation struct {
	Start                int64    `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  int64    `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexSliceLocation) Reset()         { *m = IndexSliceLocation{} }
func (m *IndexSliceLocation) String() string { return proto.CompactTextString(m) }
func (*IndexSliceLocation) ProtoMessage()    {}
func (*IndexSliceLocation) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{5}
}
func (m *IndexSliceLocation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSliceLocation.Unmarshal(m, b)
}
func (m *IndexSliceLocation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSliceLocation.Marshal(b, m, deterministic)
}
func (dst *IndexSliceLocation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSliceLocation.Merge(dst, src)
}
func (m *IndexSliceLocation) XXX_Size() int {
	return xxx_messageInfo_IndexSliceLocation.Size(m)
}
func (m *IndexSliceLocation) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSliceLocation.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSliceLocation proto.InternalMessageInfo

func (m *IndexSliceLocation) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *IndexSliceLocation) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *IndexSliceLocation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type IndexSlice struct {
	Entries              []*IndexEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IndexSlice) Reset()         { *m = IndexSlice{} }
func (m *IndexSlice) String() string { return proto.CompactTextString(m) }
func (*IndexSlice) ProtoMessage()    {}
func (*IndexSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{6}
}
func (m *IndexSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexSlice.Unmarshal(m, b)
}
func (m *IndexSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexSlice.Marshal(b, m, deterministic)
}
func (dst *IndexSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexSlice.Merge(dst, src)
}
func (m *IndexSlice) XXX_Size() int {
	return xxx_messageInfo_IndexSlice.Size(m)
}
func (m *IndexSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexSlice.DiscardUnknown(m)
}

var xxx_messageInfo_IndexSlice proto.InternalMessageInfo

func (m *IndexSlice) GetEntries() []*IndexEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type IndexEntry struct {
	// Types that are valid to be assigned to Entry:
	//	*IndexEntry_Hash
	//	*IndexEntry_Fill
	Entry                isIndexEntry_Entry `protobuf_oneof:"entry"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *IndexEntry) Reset()         { *m = IndexEntry{} }
func (m *IndexEntry) String() string { return proto.CompactTextString(m) }
func (*IndexEntry) ProtoMessage()    {}
func (*IndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{7}
}
func (m *IndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexEntry.Unmarshal(m, b)
}
func (m *IndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexEntry.Marshal(b, m, deterministic)
}
func (dst *IndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexEntry.Merge(dst, src)
}
func (m *IndexEntry) XXX_Size() int {
	return xxx_messageInfo_IndexEntry.Size(m)
}
func (m *IndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_IndexEntry proto.InternalMessageInfo

type isIndexEntry_Entry interface {
	isIndexEntry_Entry()
}

type IndexEntry_Hash struct {
	Hash *HashIndexEntry `protobuf:"bytes,1,opt,name=hash,proto3,oneof"`
}

type IndexEntry_Fill struct {
	Fill *FillIndexEntry `protobuf:"bytes,2,opt,name=fill,proto3,oneof"`
}

func (*IndexEntry_Hash) isIndexEntry_Entry() {}

func (*IndexEntry_Fill) isIndexEntry_Entry() {}

func (m *IndexEntry) GetEntry() isIndexEntry_Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *IndexEntry) GetHash() *HashIndexEntry {
	if x, ok := m.GetEntry().(*IndexEntry_Hash); ok {
		return x.Hash
	}
	return nil
}

func (m *IndexEntry) GetFill() *FillIndexEntry {
	if x, ok := m.GetEntry().(*IndexEntry_Fill); ok {
		return x.Fill
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*IndexEntry) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _IndexEntry_OneofMarshaler, _IndexEntry_OneofUnmarshaler, _IndexEntry_OneofSizer, []interface{}{
		(*IndexEntry_Hash)(nil),
		(*IndexEntry_Fill)(nil),
	}
}

func _IndexEntry_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*IndexEntry)
	// entry
	switch x := m.Entry.(type) {
	case *IndexEntry_Hash:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Hash); err != nil {
			return err
		}
	case *IndexEntry_Fill:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fill); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("IndexEntry.Entry has unexpected type %T", x)
	}
	return nil
}

func _IndexEntry_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*IndexEntry)
	switch tag {
	case 1: // entry.hash
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HashIndexEntry)
		err := b.DecodeMessage(msg)
		m.Entry = &IndexEntry_Hash{msg}
		return true, err
	case 2: // entry.fill
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FillIndexEntry)
		err := b.DecodeMessage(msg)
		m.Entry = &IndexEntry_Fill{msg}
		return true, err
	default:
		return false, nil
	}
}

func _IndexEntry_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*IndexEntry)
	// entry
	switch x := m.Entry.(type) {
	case *IndexEntry_Hash:
		s := proto.Size(x.Hash)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *IndexEntry_Fill:
		s := proto.Size(x.Fill)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HashIndexEntry struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashIndexEntry) Reset()         { *m = HashIndexEntry{} }
func (m *HashIndexEntry) String() string { return proto.CompactTextString(m) }
func (*HashIndexEntry) ProtoMessage()    {}
func (*HashIndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{8}
}
func (m *HashIndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashIndexEntry.Unmarshal(m, b)
}
func (m *HashIndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashIndexEntry.Marshal(b, m, deterministic)
}
func (dst *HashIndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashIndexEntry.Merge(dst, src)
}
func (m *HashIndexEntry) XXX_Size() int {
	return xxx_messageInfo_HashIndexEntry.Size(m)
}
func (m *HashIndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_HashIndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_HashIndexEntry proto.InternalMessageInfo

func (m *HashIndexEntry) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *HashIndexEntry) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type FillIndexEntry struct {
	Size                 int32    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Byte                 int32    `protobuf:"varint,2,opt,name=byte,proto3" json:"byte,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FillIndexEntry) Reset()         { *m = FillIndexEntry{} }
func (m *FillIndexEntry) String() string { return proto.CompactTextString(m) }
func (*FillIndexEntry) ProtoMessage()    {}
func (*FillIndexEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{9}
}
func (m *FillIndexEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FillIndexEntry.Unmarshal(m, b)
}
func (m *FillIndexEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FillIndexEntry.Marshal(b, m, deterministic)
}
func (dst *FillIndexEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FillIndexEntry.Merge(dst, src)
}
func (m *FillIndexEntry) XXX_Size() int {
	return xxx_messageInfo_FillIndexEntry.Size(m)
}
func (m *FillIndexEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FillIndexEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FillIndexEntry proto.InternalMessageInfo

func (m *FillIndexEntry) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *FillIndexEntry) GetByte() int32 {
	if m != nil {
		return m.Byte
	}
	return 0
}

type IndexResponseHeader struct {
	Revision             int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IndexResponseHeader) Reset()         { *m = IndexResponseHeader{} }
func (m *IndexResponseHeader) String() string { return proto.CompactTextString(m) }
func (*IndexResponseHeader) ProtoMessage()    {}
func (*IndexResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_index_136b23d3185761ba, []int{10}
}
func (m *IndexResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IndexResponseHeader.Unmarshal(m, b)
}
func (m *IndexResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IndexResponseHeader.Marshal(b, m, deterministic)
}
func (dst *IndexResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndexResponseHeader.Merge(dst, src)
}
func (m *IndexResponseHeader) XXX_Size() int {
	return xxx_messageInfo_IndexResponseHeader.Size(m)
}
func (m *IndexResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_IndexResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_IndexResponseHeader proto.InternalMessageInfo

func (m *IndexResponseHeader) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *IndexResponseHeader) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *IndexResponseHeader) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*IndexGetRangeRequest)(nil), "api.IndexGetRangeRequest")
	proto.RegisterType((*IndexGetRangeResponse)(nil), "api.IndexGetRangeResponse")
	proto.RegisterType((*IndexGetRangeResponse_Info)(nil), "api.IndexGetRangeResponse.Info")
	proto.RegisterType((*IndexGetRangeResponse_Data)(nil), "api.IndexGetRangeResponse.Data")
	proto.RegisterType((*IndexPutRangeRequest)(nil), "api.IndexPutRangeRequest")
	proto.RegisterType((*IndexPutRangeRequest_Info)(nil), "api.IndexPutRangeRequest.Info")
	proto.RegisterType((*IndexPutRangeRequest_Data)(nil), "api.IndexPutRangeRequest.Data")
	proto.RegisterType((*IndexPutRangeResponse)(nil), "api.IndexPutRangeResponse")
	proto.RegisterType((*IndexShard)(nil), "api.IndexShard")
	proto.RegisterType((*IndexSliceLocation)(nil), "api.IndexSliceLocation")
	proto.RegisterType((*IndexSlice)(nil), "api.IndexSlice")
	proto.RegisterType((*IndexEntry)(nil), "api.IndexEntry")
	proto.RegisterType((*HashIndexEntry)(nil), "api.HashIndexEntry")
	proto.RegisterType((*FillIndexEntry)(nil), "api.FillIndexEntry")
	proto.RegisterType((*IndexResponseHeader)(nil), "api.IndexResponseHeader")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IndexStoreClient is the client API for IndexStore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexStoreClient interface {
	GetRange(ctx context.Context, in *IndexGetRangeRequest, opts ...grpc.CallOption) (IndexStore_GetRangeClient, error)
	PutRange(ctx context.Context, opts ...grpc.CallOption) (IndexStore_PutRangeClient, error)
}

type indexStoreClient struct {
	cc *grpc.ClientConn
}

func NewIndexStoreClient(cc *grpc.ClientConn) IndexStoreClient {
	return &indexStoreClient{cc}
}

func (c *indexStoreClient) GetRange(ctx context.Context, in *IndexGetRangeRequest, opts ...grpc.CallOption) (IndexStore_GetRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IndexStore_serviceDesc.Streams[0], "/api.IndexStore/GetRange", opts...)
	if err != nil {
		return nil, err
	}
	x := &indexStoreGetRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IndexStore_GetRangeClient interface {
	Recv() (*IndexGetRangeResponse, error)
	grpc.ClientStream
}

type indexStoreGetRangeClient struct {
	grpc.ClientStream
}

func (x *indexStoreGetRangeClient) Recv() (*IndexGetRangeResponse, error) {
	m := new(IndexGetRangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *indexStoreClient) PutRange(ctx context.Context, opts ...grpc.CallOption) (IndexStore_PutRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_IndexStore_serviceDesc.Streams[1], "/api.IndexStore/PutRange", opts...)
	if err != nil {
		return nil, err
	}
	x := &indexStorePutRangeClient{stream}
	return x, nil
}

type IndexStore_PutRangeClient interface {
	Send(*IndexPutRangeRequest) error
	CloseAndRecv() (*IndexPutRangeResponse, error)
	grpc.ClientStream
}

type indexStorePutRangeClient struct {
	grpc.ClientStream
}

func (x *indexStorePutRangeClient) Send(m *IndexPutRangeRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *indexStorePutRangeClient) CloseAndRecv() (*IndexPutRangeResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(IndexPutRangeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// IndexStoreServer is the server API for IndexStore service.
type IndexStoreServer interface {
	GetRange(*IndexGetRangeRequest, IndexStore_GetRangeServer) error
	PutRange(IndexStore_PutRangeServer) error
}

func RegisterIndexStoreServer(s *grpc.Server, srv IndexStoreServer) {
	s.RegisterService(&_IndexStore_serviceDesc, srv)
}

func _IndexStore_GetRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IndexGetRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IndexStoreServer).GetRange(m, &indexStoreGetRangeServer{stream})
}

type IndexStore_GetRangeServer interface {
	Send(*IndexGetRangeResponse) error
	grpc.ServerStream
}

type indexStoreGetRangeServer struct {
	grpc.ServerStream
}

func (x *indexStoreGetRangeServer) Send(m *IndexGetRangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _IndexStore_PutRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IndexStoreServer).PutRange(&indexStorePutRangeServer{stream})
}

type IndexStore_PutRangeServer interface {
	SendAndClose(*IndexPutRangeResponse) error
	Recv() (*IndexPutRangeRequest, error)
	grpc.ServerStream
}

type indexStorePutRangeServer struct {
	grpc.ServerStream
}

func (x *indexStorePutRangeServer) SendAndClose(m *IndexPutRangeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *indexStorePutRangeServer) Recv() (*IndexPutRangeRequest, error) {
	m := new(IndexPutRangeRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _IndexStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.IndexStore",
	HandlerType: (*IndexStoreServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRange",
			Handler:       _IndexStore_GetRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutRange",
			Handler:       _IndexStore_PutRange_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "index.proto",
}

func init() { proto.RegisterFile("index.proto", fileDescriptor_index_136b23d3185761ba) }

var fileDescriptor_index_136b23d3185761ba = []byte{
	// 551 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0x13, 0x31,
	0x10, 0xed, 0x7e, 0xa5, 0xc9, 0x04, 0x15, 0xe4, 0x06, 0xb1, 0x04, 0x09, 0x22, 0x4b, 0x48, 0xe9,
	0x81, 0x50, 0x85, 0x22, 0x38, 0x57, 0x14, 0x12, 0xa9, 0x48, 0xc8, 0x70, 0xe1, 0x04, 0x6e, 0xd7,
	0x49, 0x2c, 0x52, 0x3b, 0xd8, 0x2e, 0x22, 0xfc, 0x94, 0x4a, 0xfc, 0x57, 0x64, 0xaf, 0xb7, 0x9b,
	0xdd, 0x6e, 0x23, 0x10, 0x37, 0x7b, 0xfc, 0xde, 0x9b, 0xf1, 0x9b, 0xb1, 0xa1, 0xcb, 0x45, 0xc6,
	0x7e, 0x8e, 0x56, 0x4a, 0x1a, 0x89, 0x22, 0xba, 0xe2, 0xf8, 0x13, 0xf4, 0xa6, 0x36, 0xf6, 0x8e,
	0x19, 0x42, 0xc5, 0x9c, 0x11, 0xf6, 0xfd, 0x92, 0x69, 0x83, 0x7a, 0x90, 0xe8, 0x05, 0x55, 0x59,
	0x1a, 0x0c, 0x82, 0x61, 0x87, 0xe4, 0x1b, 0x17, 0x35, 0x54, 0x99, 0x34, 0x1c, 0x04, 0xc3, 0x88,
	0xe4, 0x1b, 0x74, 0x0f, 0x22, 0x26, 0xb2, 0x34, 0x72, 0x31, 0xbb, 0xc4, 0xbf, 0x43, 0xb8, 0x5f,
	0x93, 0xd5, 0x2b, 0x29, 0x34, 0x43, 0x2f, 0x21, 0xe6, 0x62, 0x26, 0x9d, 0x6c, 0x77, 0xfc, 0x64,
	0x44, 0x57, 0x7c, 0xd4, 0x88, 0x1c, 0x4d, 0xc5, 0x4c, 0x4e, 0x76, 0x88, 0x83, 0x5b, 0x5a, 0x46,
	0x0d, 0x75, 0x79, 0xb7, 0xd3, 0xde, 0x50, 0x43, 0x2d, 0xcd, 0xc2, 0xfb, 0x5f, 0x21, 0xb6, 0x32,
	0xe8, 0x10, 0x5a, 0x0b, 0x46, 0x33, 0xa6, 0x7c, 0xde, 0xb4, 0x14, 0x28, 0x88, 0x13, 0x77, 0x4e,
	0x3c, 0xee, 0x6f, 0x6f, 0xda, 0x7f, 0x06, 0xb1, 0xcd, 0x88, 0x9e, 0x42, 0xa2, 0x97, 0xfc, 0x9c,
	0xf9, 0x04, 0x77, 0xcb, 0x04, 0x1f, 0x6d, 0x98, 0xe4, 0xa7, 0xc7, 0x09, 0x44, 0x17, 0x7a, 0x8e,
	0xaf, 0x42, 0x6f, 0xfb, 0x87, 0xcb, 0xaa, 0xed, 0x47, 0x15, 0x7b, 0x1e, 0x97, 0x2a, 0x35, 0x60,
	0xd5, 0x9d, 0xa3, 0x8a, 0x3b, 0x5b, 0x58, 0x8d, 0xe6, 0x34, 0xb7, 0xba, 0x0f, 0x6d, 0xc5, 0x7e,
	0x70, 0xcd, 0xa5, 0xf0, 0x1e, 0x5c, 0xef, 0x4b, 0x73, 0xa2, 0x06, 0x73, 0xe2, 0xff, 0x35, 0x67,
	0xea, 0x67, 0xa7, 0x2c, 0xde, 0xcf, 0xce, 0x3f, 0x77, 0x11, 0x7f, 0x06, 0xc8, 0xd3, 0xdc, 0xb8,
	0x52, 0x50, 0xbb, 0xd2, 0x73, 0x68, 0xb9, 0x22, 0x74, 0x1a, 0x0e, 0xa2, 0x61, 0x77, 0xfc, 0xa0,
	0x56, 0xe3, 0xa9, 0x3c, 0xa7, 0x86, 0x4b, 0x41, 0x3c, 0x0c, 0x9f, 0x02, 0xba, 0x79, 0x5a, 0x3a,
	0x13, 0x34, 0x38, 0x13, 0x5e, 0x3b, 0x83, 0xf6, 0x20, 0xe4, 0xf9, 0x1c, 0x75, 0x48, 0xc8, 0x33,
	0xfc, 0xaa, 0x28, 0xd4, 0xaa, 0xa1, 0x03, 0xd8, 0x65, 0xc2, 0x28, 0xce, 0x74, 0x1a, 0xb8, 0x6a,
	0x36, 0x1c, 0x3b, 0x11, 0x46, 0xad, 0x49, 0x71, 0x8e, 0xbf, 0x79, 0xa2, 0x0b, 0xa3, 0x03, 0x88,
	0x17, 0x54, 0x2f, 0xbc, 0x3f, 0xfb, 0x8e, 0x35, 0xa1, 0x7a, 0x51, 0x42, 0x6c, 0xf7, 0x2d, 0xc4,
	0x42, 0x67, 0x7c, 0xb9, 0xf4, 0x33, 0x93, 0x43, 0xdf, 0xf2, 0xe5, 0xb2, 0x0a, 0xb5, 0x90, 0xe3,
	0x5d, 0x48, 0x6c, 0xba, 0x35, 0x7e, 0x0d, 0x7b, 0x55, 0x35, 0x84, 0x20, 0xd6, 0xfc, 0x57, 0xde,
	0xd8, 0x84, 0xb8, 0xb5, 0x8d, 0xb9, 0x22, 0xac, 0xf2, 0x9d, 0x3c, 0x9b, 0x65, 0x56, 0xc5, 0x6f,
	0x63, 0x9e, 0xad, 0x0d, 0x73, 0xcc, 0x84, 0xb8, 0x35, 0xce, 0x60, 0xbf, 0xa1, 0xc3, 0x5b, 0x7b,
	0xd9, 0x83, 0x84, 0x29, 0x25, 0x95, 0xd7, 0xc9, 0x37, 0xe8, 0x11, 0x74, 0xdc, 0xe2, 0xcb, 0x85,
	0x9e, 0x7b, 0xe7, 0xdb, 0x2e, 0xf0, 0x5e, 0xcf, 0xc7, 0x57, 0x41, 0xd1, 0x00, 0x23, 0x15, 0x43,
	0x27, 0xd0, 0x2e, 0x3e, 0x16, 0xf4, 0xb0, 0xe9, 0xb3, 0x71, 0xcf, 0xa9, 0xdf, 0xbf, 0xfd, 0x1f,
	0xc2, 0x3b, 0x87, 0x81, 0x95, 0x29, 0x86, 0x78, 0x53, 0xa6, 0xf6, 0x2a, 0x37, 0x65, 0xea, 0x33,
	0x8f, 0x77, 0x86, 0xc1, 0x59, 0xcb, 0xfd, 0xd7, 0x2f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xbd,
	0xdd, 0x17, 0xda, 0xbe, 0x05, 0x00, 0x00,
}
