// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitor.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HashAlgorithm int32

const (
	HashAlgorithm_SHA256      HashAlgorithm = 0
	HashAlgorithm_MURMURHASH3 HashAlgorithm = 1
	HashAlgorithm_RIPEMD160   HashAlgorithm = 2
)

var HashAlgorithm_name = map[int32]string{
	0: "SHA256",
	1: "MURMURHASH3",
	2: "RIPEMD160",
}
var HashAlgorithm_value = map[string]int32{
	"SHA256":      0,
	"MURMURHASH3": 1,
	"RIPEMD160":   2,
}

func (x HashAlgorithm) String() string {
	return proto.EnumName(HashAlgorithm_name, int32(x))
}
func (HashAlgorithm) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{0}
}

type VolumeState int32

const (
	VolumeState_NEW      VolumeState = 0
	VolumeState_CREATED  VolumeState = 1
	VolumeState_RESIZING VolumeState = 2
	VolumeState_DELETING VolumeState = 3
	VolumeState_DELETED  VolumeState = 4
)

var VolumeState_name = map[int32]string{
	0: "NEW",
	1: "CREATED",
	2: "RESIZING",
	3: "DELETING",
	4: "DELETED",
}
var VolumeState_value = map[string]int32{
	"NEW":      0,
	"CREATED":  1,
	"RESIZING": 2,
	"DELETING": 3,
	"DELETED":  4,
}

func (x VolumeState) String() string {
	return proto.EnumName(VolumeState_name, int32(x))
}
func (VolumeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{1}
}

type ClientSettingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSettingsRequest) Reset()         { *m = ClientSettingsRequest{} }
func (m *ClientSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ClientSettingsRequest) ProtoMessage()    {}
func (*ClientSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{0}
}
func (m *ClientSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSettingsRequest.Unmarshal(m, b)
}
func (m *ClientSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSettingsRequest.Marshal(b, m, deterministic)
}
func (dst *ClientSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSettingsRequest.Merge(dst, src)
}
func (m *ClientSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_ClientSettingsRequest.Size(m)
}
func (m *ClientSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSettingsRequest proto.InternalMessageInfo

type ClientSettingsResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Settings             *ClientSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ClientSettingsResponse) Reset()         { *m = ClientSettingsResponse{} }
func (m *ClientSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*ClientSettingsResponse) ProtoMessage()    {}
func (*ClientSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{1}
}
func (m *ClientSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSettingsResponse.Unmarshal(m, b)
}
func (m *ClientSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSettingsResponse.Marshal(b, m, deterministic)
}
func (dst *ClientSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSettingsResponse.Merge(dst, src)
}
func (m *ClientSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_ClientSettingsResponse.Size(m)
}
func (m *ClientSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSettingsResponse proto.InternalMessageInfo

func (m *ClientSettingsResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ClientSettingsResponse) GetSettings() *ClientSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ClientSettings struct {
	MinFillSize int32         `protobuf:"varint,1,opt,name=min_fill_size,json=minFillSize,proto3" json:"min_fill_size,omitempty"`
	HashAlgo    HashAlgorithm `protobuf:"varint,2,opt,name=hash_algo,json=hashAlgo,proto3,enum=api.HashAlgorithm" json:"hash_algo,omitempty"`
	// Types that are valid to be assigned to ChunkAlgo:
	//	*ClientSettings_Rabin
	//	*ClientSettings_Fixed
	//	*ClientSettings_Fastcdc
	ChunkAlgo            isClientSettings_ChunkAlgo `protobuf_oneof:"chunk_algo"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *ClientSettings) Reset()         { *m = ClientSettings{} }
func (m *ClientSettings) String() string { return proto.CompactTextString(m) }
func (*ClientSettings) ProtoMessage()    {}
func (*ClientSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{2}
}
func (m *ClientSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSettings.Unmarshal(m, b)
}
func (m *ClientSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSettings.Marshal(b, m, deterministic)
}
func (dst *ClientSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSettings.Merge(dst, src)
}
func (m *ClientSettings) XXX_Size() int {
	return xxx_messageInfo_ClientSettings.Size(m)
}
func (m *ClientSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSettings proto.InternalMessageInfo

func (m *ClientSettings) GetMinFillSize() int32 {
	if m != nil {
		return m.MinFillSize
	}
	return 0
}

func (m *ClientSettings) GetHashAlgo() HashAlgorithm {
	if m != nil {
		return m.HashAlgo
	}
	return HashAlgorithm_SHA256
}

type isClientSettings_ChunkAlgo interface {
	isClientSettings_ChunkAlgo()
}

type ClientSettings_Rabin struct {
	Rabin *RabinChunkAlgorithm `protobuf:"bytes,3,opt,name=rabin,proto3,oneof"`
}

type ClientSettings_Fixed struct {
	Fixed *FixedChunkAlgorithm `protobuf:"bytes,4,opt,name=fixed,proto3,oneof"`
}

type ClientSettings_Fastcdc struct {
	Fastcdc *FastCDCChunkAlgorithm `protobuf:"bytes,5,opt,name=fastcdc,proto3,oneof"`
}

func (*ClientSettings_Rabin) isClientSettings_ChunkAlgo() {}

func (*ClientSettings_Fixed) isClientSettings_ChunkAlgo() {}

func (*ClientSettings_Fastcdc) isClientSettings_ChunkAlgo() {}

func (m *ClientSettings) GetChunkAlgo() isClientSettings_ChunkAlgo {
	if m != nil {
		return m.ChunkAlgo
	}
	return nil
}

func (m *ClientSettings) GetRabin() *RabinChunkAlgorithm {
	if x, ok := m.GetChunkAlgo().(*ClientSettings_Rabin); ok {
		return x.Rabin
	}
	return nil
}

func (m *ClientSettings) GetFixed() *FixedChunkAlgorithm {
	if x, ok := m.GetChunkAlgo().(*ClientSettings_Fixed); ok {
		return x.Fixed
	}
	return nil
}

func (m *ClientSettings) GetFastcdc() *FastCDCChunkAlgorithm {
	if x, ok := m.GetChunkAlgo().(*ClientSettings_Fastcdc); ok {
		return x.Fastcdc
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ClientSettings) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ClientSettings_OneofMarshaler, _ClientSettings_OneofUnmarshaler, _ClientSettings_OneofSizer, []interface{}{
		(*ClientSettings_Rabin)(nil),
		(*ClientSettings_Fixed)(nil),
		(*ClientSettings_Fastcdc)(nil),
	}
}

func _ClientSettings_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ClientSettings)
	// chunk_algo
	switch x := m.ChunkAlgo.(type) {
	case *ClientSettings_Rabin:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Rabin); err != nil {
			return err
		}
	case *ClientSettings_Fixed:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fixed); err != nil {
			return err
		}
	case *ClientSettings_Fastcdc:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fastcdc); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ClientSettings.ChunkAlgo has unexpected type %T", x)
	}
	return nil
}

func _ClientSettings_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ClientSettings)
	switch tag {
	case 3: // chunk_algo.rabin
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RabinChunkAlgorithm)
		err := b.DecodeMessage(msg)
		m.ChunkAlgo = &ClientSettings_Rabin{msg}
		return true, err
	case 4: // chunk_algo.fixed
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FixedChunkAlgorithm)
		err := b.DecodeMessage(msg)
		m.ChunkAlgo = &ClientSettings_Fixed{msg}
		return true, err
	case 5: // chunk_algo.fastcdc
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FastCDCChunkAlgorithm)
		err := b.DecodeMessage(msg)
		m.ChunkAlgo = &ClientSettings_Fastcdc{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ClientSettings_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ClientSettings)
	// chunk_algo
	switch x := m.ChunkAlgo.(type) {
	case *ClientSettings_Rabin:
		s := proto.Size(x.Rabin)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientSettings_Fixed:
		s := proto.Size(x.Fixed)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ClientSettings_Fastcdc:
		s := proto.Size(x.Fastcdc)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type RabinChunkAlgorithm struct {
	Poly                 uint64   `protobuf:"varint,1,opt,name=poly,proto3" json:"poly,omitempty"`
	MaxSize              int32    `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MinSize              int32    `protobuf:"varint,3,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RabinChunkAlgorithm) Reset()         { *m = RabinChunkAlgorithm{} }
func (m *RabinChunkAlgorithm) String() string { return proto.CompactTextString(m) }
func (*RabinChunkAlgorithm) ProtoMessage()    {}
func (*RabinChunkAlgorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{3}
}
func (m *RabinChunkAlgorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RabinChunkAlgorithm.Unmarshal(m, b)
}
func (m *RabinChunkAlgorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RabinChunkAlgorithm.Marshal(b, m, deterministic)
}
func (dst *RabinChunkAlgorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RabinChunkAlgorithm.Merge(dst, src)
}
func (m *RabinChunkAlgorithm) XXX_Size() int {
	return xxx_messageInfo_RabinChunkAlgorithm.Size(m)
}
func (m *RabinChunkAlgorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_RabinChunkAlgorithm.DiscardUnknown(m)
}

var xxx_messageInfo_RabinChunkAlgorithm proto.InternalMessageInfo

func (m *RabinChunkAlgorithm) GetPoly() uint64 {
	if m != nil {
		return m.Poly
	}
	return 0
}

func (m *RabinChunkAlgorithm) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *RabinChunkAlgorithm) GetMinSize() int32 {
	if m != nil {
		return m.MinSize
	}
	return 0
}

type FixedChunkAlgorithm struct {
	MaxSize              int32    `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FixedChunkAlgorithm) Reset()         { *m = FixedChunkAlgorithm{} }
func (m *FixedChunkAlgorithm) String() string { return proto.CompactTextString(m) }
func (*FixedChunkAlgorithm) ProtoMessage()    {}
func (*FixedChunkAlgorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{4}
}
func (m *FixedChunkAlgorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FixedChunkAlgorithm.Unmarshal(m, b)
}
func (m *FixedChunkAlgorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FixedChunkAlgorithm.Marshal(b, m, deterministic)
}
func (dst *FixedChunkAlgorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedChunkAlgorithm.Merge(dst, src)
}
func (m *FixedChunkAlgorithm) XXX_Size() int {
	return xxx_messageInfo_FixedChunkAlgorithm.Size(m)
}
func (m *FixedChunkAlgorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedChunkAlgorithm.DiscardUnknown(m)
}

var xxx_messageInfo_FixedChunkAlgorithm proto.InternalMessageInfo

func (m *FixedChunkAlgorithm) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

type FastCDCChunkAlgorithm struct {
	MaxSize              int32    `protobuf:"varint,1,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	MinSize              int32    `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	AvgSize              int32    `protobuf:"varint,3,opt,name=avg_size,json=avgSize,proto3" json:"avg_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FastCDCChunkAlgorithm) Reset()         { *m = FastCDCChunkAlgorithm{} }
func (m *FastCDCChunkAlgorithm) String() string { return proto.CompactTextString(m) }
func (*FastCDCChunkAlgorithm) ProtoMessage()    {}
func (*FastCDCChunkAlgorithm) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{5}
}
func (m *FastCDCChunkAlgorithm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FastCDCChunkAlgorithm.Unmarshal(m, b)
}
func (m *FastCDCChunkAlgorithm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FastCDCChunkAlgorithm.Marshal(b, m, deterministic)
}
func (dst *FastCDCChunkAlgorithm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FastCDCChunkAlgorithm.Merge(dst, src)
}
func (m *FastCDCChunkAlgorithm) XXX_Size() int {
	return xxx_messageInfo_FastCDCChunkAlgorithm.Size(m)
}
func (m *FastCDCChunkAlgorithm) XXX_DiscardUnknown() {
	xxx_messageInfo_FastCDCChunkAlgorithm.DiscardUnknown(m)
}

var xxx_messageInfo_FastCDCChunkAlgorithm proto.InternalMessageInfo

func (m *FastCDCChunkAlgorithm) GetMaxSize() int32 {
	if m != nil {
		return m.MaxSize
	}
	return 0
}

func (m *FastCDCChunkAlgorithm) GetMinSize() int32 {
	if m != nil {
		return m.MinSize
	}
	return 0
}

func (m *FastCDCChunkAlgorithm) GetAvgSize() int32 {
	if m != nil {
		return m.AvgSize
	}
	return 0
}

type ServerSettingsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSettingsRequest) Reset()         { *m = ServerSettingsRequest{} }
func (m *ServerSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*ServerSettingsRequest) ProtoMessage()    {}
func (*ServerSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{6}
}
func (m *ServerSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSettingsRequest.Unmarshal(m, b)
}
func (m *ServerSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSettingsRequest.Marshal(b, m, deterministic)
}
func (dst *ServerSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSettingsRequest.Merge(dst, src)
}
func (m *ServerSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_ServerSettingsRequest.Size(m)
}
func (m *ServerSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSettingsRequest proto.InternalMessageInfo

type ServerSettingsResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Settings             *ServerSettings        `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServerSettingsResponse) Reset()         { *m = ServerSettingsResponse{} }
func (m *ServerSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*ServerSettingsResponse) ProtoMessage()    {}
func (*ServerSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{7}
}
func (m *ServerSettingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSettingsResponse.Unmarshal(m, b)
}
func (m *ServerSettingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSettingsResponse.Marshal(b, m, deterministic)
}
func (dst *ServerSettingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSettingsResponse.Merge(dst, src)
}
func (m *ServerSettingsResponse) XXX_Size() int {
	return xxx_messageInfo_ServerSettingsResponse.Size(m)
}
func (m *ServerSettingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSettingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSettingsResponse proto.InternalMessageInfo

func (m *ServerSettingsResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ServerSettingsResponse) GetSettings() *ServerSettings {
	if m != nil {
		return m.Settings
	}
	return nil
}

type ServerSettings struct {
	ShardSize            int64    `protobuf:"varint,1,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSettings) Reset()         { *m = ServerSettings{} }
func (m *ServerSettings) String() string { return proto.CompactTextString(m) }
func (*ServerSettings) ProtoMessage()    {}
func (*ServerSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{8}
}
func (m *ServerSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSettings.Unmarshal(m, b)
}
func (m *ServerSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSettings.Marshal(b, m, deterministic)
}
func (dst *ServerSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSettings.Merge(dst, src)
}
func (m *ServerSettings) XXX_Size() int {
	return xxx_messageInfo_ServerSettings.Size(m)
}
func (m *ServerSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSettings.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSettings proto.InternalMessageInfo

func (m *ServerSettings) GetShardSize() int64 {
	if m != nil {
		return m.ShardSize
	}
	return 0
}

type GetBlockStoresRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBlockStoresRequest) Reset()         { *m = GetBlockStoresRequest{} }
func (m *GetBlockStoresRequest) String() string { return proto.CompactTextString(m) }
func (*GetBlockStoresRequest) ProtoMessage()    {}
func (*GetBlockStoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{9}
}
func (m *GetBlockStoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockStoresRequest.Unmarshal(m, b)
}
func (m *GetBlockStoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockStoresRequest.Marshal(b, m, deterministic)
}
func (dst *GetBlockStoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockStoresRequest.Merge(dst, src)
}
func (m *GetBlockStoresRequest) XXX_Size() int {
	return xxx_messageInfo_GetBlockStoresRequest.Size(m)
}
func (m *GetBlockStoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockStoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockStoresRequest proto.InternalMessageInfo

type GetBlockStoresResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nodes                []*NodeReplicaSet      `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetBlockStoresResponse) Reset()         { *m = GetBlockStoresResponse{} }
func (m *GetBlockStoresResponse) String() string { return proto.CompactTextString(m) }
func (*GetBlockStoresResponse) ProtoMessage()    {}
func (*GetBlockStoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{10}
}
func (m *GetBlockStoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBlockStoresResponse.Unmarshal(m, b)
}
func (m *GetBlockStoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBlockStoresResponse.Marshal(b, m, deterministic)
}
func (dst *GetBlockStoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBlockStoresResponse.Merge(dst, src)
}
func (m *GetBlockStoresResponse) XXX_Size() int {
	return xxx_messageInfo_GetBlockStoresResponse.Size(m)
}
func (m *GetBlockStoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBlockStoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBlockStoresResponse proto.InternalMessageInfo

func (m *GetBlockStoresResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetBlockStoresResponse) GetNodes() []*NodeReplicaSet {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type GetIndexStoresRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetIndexStoresRequest) Reset()         { *m = GetIndexStoresRequest{} }
func (m *GetIndexStoresRequest) String() string { return proto.CompactTextString(m) }
func (*GetIndexStoresRequest) ProtoMessage()    {}
func (*GetIndexStoresRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{11}
}
func (m *GetIndexStoresRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexStoresRequest.Unmarshal(m, b)
}
func (m *GetIndexStoresRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexStoresRequest.Marshal(b, m, deterministic)
}
func (dst *GetIndexStoresRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexStoresRequest.Merge(dst, src)
}
func (m *GetIndexStoresRequest) XXX_Size() int {
	return xxx_messageInfo_GetIndexStoresRequest.Size(m)
}
func (m *GetIndexStoresRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexStoresRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexStoresRequest proto.InternalMessageInfo

type GetIndexStoresResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Nodes                []*NodeReplicaSet      `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetIndexStoresResponse) Reset()         { *m = GetIndexStoresResponse{} }
func (m *GetIndexStoresResponse) String() string { return proto.CompactTextString(m) }
func (*GetIndexStoresResponse) ProtoMessage()    {}
func (*GetIndexStoresResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{12}
}
func (m *GetIndexStoresResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetIndexStoresResponse.Unmarshal(m, b)
}
func (m *GetIndexStoresResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetIndexStoresResponse.Marshal(b, m, deterministic)
}
func (dst *GetIndexStoresResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetIndexStoresResponse.Merge(dst, src)
}
func (m *GetIndexStoresResponse) XXX_Size() int {
	return xxx_messageInfo_GetIndexStoresResponse.Size(m)
}
func (m *GetIndexStoresResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetIndexStoresResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetIndexStoresResponse proto.InternalMessageInfo

func (m *GetIndexStoresResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetIndexStoresResponse) GetNodes() []*NodeReplicaSet {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type NodeReplicaSet struct {
	Slot                 int64    `protobuf:"varint,1,opt,name=slot,proto3" json:"slot,omitempty"`
	Nodes                []*Node  `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeReplicaSet) Reset()         { *m = NodeReplicaSet{} }
func (m *NodeReplicaSet) String() string { return proto.CompactTextString(m) }
func (*NodeReplicaSet) ProtoMessage()    {}
func (*NodeReplicaSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{13}
}
func (m *NodeReplicaSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReplicaSet.Unmarshal(m, b)
}
func (m *NodeReplicaSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReplicaSet.Marshal(b, m, deterministic)
}
func (dst *NodeReplicaSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReplicaSet.Merge(dst, src)
}
func (m *NodeReplicaSet) XXX_Size() int {
	return xxx_messageInfo_NodeReplicaSet.Size(m)
}
func (m *NodeReplicaSet) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReplicaSet.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReplicaSet proto.InternalMessageInfo

func (m *NodeReplicaSet) GetSlot() int64 {
	if m != nil {
		return m.Slot
	}
	return 0
}

func (m *NodeReplicaSet) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Primary              bool     `protobuf:"varint,3,opt,name=primary,proto3" json:"primary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{14}
}
func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (dst *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(dst, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Node) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Node) GetPrimary() bool {
	if m != nil {
		return m.Primary
	}
	return false
}

type GetVolumesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetVolumesRequest) Reset()         { *m = GetVolumesRequest{} }
func (m *GetVolumesRequest) String() string { return proto.CompactTextString(m) }
func (*GetVolumesRequest) ProtoMessage()    {}
func (*GetVolumesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{15}
}
func (m *GetVolumesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumesRequest.Unmarshal(m, b)
}
func (m *GetVolumesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumesRequest.Marshal(b, m, deterministic)
}
func (dst *GetVolumesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumesRequest.Merge(dst, src)
}
func (m *GetVolumesRequest) XXX_Size() int {
	return xxx_messageInfo_GetVolumesRequest.Size(m)
}
func (m *GetVolumesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumesRequest proto.InternalMessageInfo

type GetVolumesResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Volumes              []*Volume              `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetVolumesResponse) Reset()         { *m = GetVolumesResponse{} }
func (m *GetVolumesResponse) String() string { return proto.CompactTextString(m) }
func (*GetVolumesResponse) ProtoMessage()    {}
func (*GetVolumesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{16}
}
func (m *GetVolumesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetVolumesResponse.Unmarshal(m, b)
}
func (m *GetVolumesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetVolumesResponse.Marshal(b, m, deterministic)
}
func (dst *GetVolumesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetVolumesResponse.Merge(dst, src)
}
func (m *GetVolumesResponse) XXX_Size() int {
	return xxx_messageInfo_GetVolumesResponse.Size(m)
}
func (m *GetVolumesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetVolumesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetVolumesResponse proto.InternalMessageInfo

func (m *GetVolumesResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *GetVolumesResponse) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type CreateVolumeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shards               int64    `protobuf:"varint,2,opt,name=shards,proto3" json:"shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateVolumeRequest) Reset()         { *m = CreateVolumeRequest{} }
func (m *CreateVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeRequest) ProtoMessage()    {}
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{17}
}
func (m *CreateVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeRequest.Unmarshal(m, b)
}
func (m *CreateVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeRequest.Marshal(b, m, deterministic)
}
func (dst *CreateVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeRequest.Merge(dst, src)
}
func (m *CreateVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeRequest.Size(m)
}
func (m *CreateVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeRequest proto.InternalMessageInfo

func (m *CreateVolumeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateVolumeRequest) GetShards() int64 {
	if m != nil {
		return m.Shards
	}
	return 0
}

type CreateVolumeResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *CreateVolumeResponse) Reset()         { *m = CreateVolumeResponse{} }
func (m *CreateVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateVolumeResponse) ProtoMessage()    {}
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{18}
}
func (m *CreateVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateVolumeResponse.Unmarshal(m, b)
}
func (m *CreateVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateVolumeResponse.Marshal(b, m, deterministic)
}
func (dst *CreateVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateVolumeResponse.Merge(dst, src)
}
func (m *CreateVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateVolumeResponse.Size(m)
}
func (m *CreateVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateVolumeResponse proto.InternalMessageInfo

func (m *CreateVolumeResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type DeleteVolumeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteVolumeRequest) Reset()         { *m = DeleteVolumeRequest{} }
func (m *DeleteVolumeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeRequest) ProtoMessage()    {}
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{19}
}
func (m *DeleteVolumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeRequest.Unmarshal(m, b)
}
func (m *DeleteVolumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteVolumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeRequest.Merge(dst, src)
}
func (m *DeleteVolumeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeRequest.Size(m)
}
func (m *DeleteVolumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeRequest proto.InternalMessageInfo

func (m *DeleteVolumeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DeleteVolumeResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DeleteVolumeResponse) Reset()         { *m = DeleteVolumeResponse{} }
func (m *DeleteVolumeResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteVolumeResponse) ProtoMessage()    {}
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{20}
}
func (m *DeleteVolumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteVolumeResponse.Unmarshal(m, b)
}
func (m *DeleteVolumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteVolumeResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteVolumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteVolumeResponse.Merge(dst, src)
}
func (m *DeleteVolumeResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteVolumeResponse.Size(m)
}
func (m *DeleteVolumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteVolumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteVolumeResponse proto.InternalMessageInfo

func (m *DeleteVolumeResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type WatchVolumesRequest struct {
	Header               *WatchRequestHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *WatchVolumesRequest) Reset()         { *m = WatchVolumesRequest{} }
func (m *WatchVolumesRequest) String() string { return proto.CompactTextString(m) }
func (*WatchVolumesRequest) ProtoMessage()    {}
func (*WatchVolumesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{21}
}
func (m *WatchVolumesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchVolumesRequest.Unmarshal(m, b)
}
func (m *WatchVolumesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchVolumesRequest.Marshal(b, m, deterministic)
}
func (dst *WatchVolumesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchVolumesRequest.Merge(dst, src)
}
func (m *WatchVolumesRequest) XXX_Size() int {
	return xxx_messageInfo_WatchVolumesRequest.Size(m)
}
func (m *WatchVolumesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchVolumesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WatchVolumesRequest proto.InternalMessageInfo

func (m *WatchVolumesRequest) GetHeader() *WatchRequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type WatchVolumesResponse struct {
	Header               *WatchResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Volumes              []*Volume            `protobuf:"bytes,2,rep,name=volumes,proto3" json:"volumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *WatchVolumesResponse) Reset()         { *m = WatchVolumesResponse{} }
func (m *WatchVolumesResponse) String() string { return proto.CompactTextString(m) }
func (*WatchVolumesResponse) ProtoMessage()    {}
func (*WatchVolumesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{22}
}
func (m *WatchVolumesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchVolumesResponse.Unmarshal(m, b)
}
func (m *WatchVolumesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchVolumesResponse.Marshal(b, m, deterministic)
}
func (dst *WatchVolumesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchVolumesResponse.Merge(dst, src)
}
func (m *WatchVolumesResponse) XXX_Size() int {
	return xxx_messageInfo_WatchVolumesResponse.Size(m)
}
func (m *WatchVolumesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchVolumesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WatchVolumesResponse proto.InternalMessageInfo

func (m *WatchVolumesResponse) GetHeader() *WatchResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *WatchVolumesResponse) GetVolumes() []*Volume {
	if m != nil {
		return m.Volumes
	}
	return nil
}

type UpdateShardsRequest struct {
	VolumeName           string   `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	AddedShards          []int64  `protobuf:"varint,2,rep,packed,name=added_shards,json=addedShards,proto3" json:"added_shards,omitempty"`
	RemovedShards        []int64  `protobuf:"varint,3,rep,packed,name=removed_shards,json=removedShards,proto3" json:"removed_shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateShardsRequest) Reset()         { *m = UpdateShardsRequest{} }
func (m *UpdateShardsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateShardsRequest) ProtoMessage()    {}
func (*UpdateShardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{23}
}
func (m *UpdateShardsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShardsRequest.Unmarshal(m, b)
}
func (m *UpdateShardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShardsRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateShardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShardsRequest.Merge(dst, src)
}
func (m *UpdateShardsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateShardsRequest.Size(m)
}
func (m *UpdateShardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShardsRequest proto.InternalMessageInfo

func (m *UpdateShardsRequest) GetVolumeName() string {
	if m != nil {
		return m.VolumeName
	}
	return ""
}

func (m *UpdateShardsRequest) GetAddedShards() []int64 {
	if m != nil {
		return m.AddedShards
	}
	return nil
}

func (m *UpdateShardsRequest) GetRemovedShards() []int64 {
	if m != nil {
		return m.RemovedShards
	}
	return nil
}

type UpdateShardsResponse struct {
	Header               *MonitorResponseHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *UpdateShardsResponse) Reset()         { *m = UpdateShardsResponse{} }
func (m *UpdateShardsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateShardsResponse) ProtoMessage()    {}
func (*UpdateShardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{24}
}
func (m *UpdateShardsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateShardsResponse.Unmarshal(m, b)
}
func (m *UpdateShardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateShardsResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateShardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateShardsResponse.Merge(dst, src)
}
func (m *UpdateShardsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateShardsResponse.Size(m)
}
func (m *UpdateShardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateShardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateShardsResponse proto.InternalMessageInfo

func (m *UpdateShardsResponse) GetHeader() *MonitorResponseHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type Volume struct {
	Name                 string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                VolumeState `protobuf:"varint,2,opt,name=state,proto3,enum=api.VolumeState" json:"state,omitempty"`
	Shards               int64       `protobuf:"varint,3,opt,name=shards,proto3" json:"shards,omitempty"`
	RequestedShards      int64       `protobuf:"varint,4,opt,name=requested_shards,json=requestedShards,proto3" json:"requested_shards,omitempty"`
	CurrentShards        []int64     `protobuf:"varint,5,rep,packed,name=current_shards,json=currentShards,proto3" json:"current_shards,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Volume) Reset()         { *m = Volume{} }
func (m *Volume) String() string { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()    {}
func (*Volume) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{25}
}
func (m *Volume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Volume.Unmarshal(m, b)
}
func (m *Volume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Volume.Marshal(b, m, deterministic)
}
func (dst *Volume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Volume.Merge(dst, src)
}
func (m *Volume) XXX_Size() int {
	return xxx_messageInfo_Volume.Size(m)
}
func (m *Volume) XXX_DiscardUnknown() {
	xxx_messageInfo_Volume.DiscardUnknown(m)
}

var xxx_messageInfo_Volume proto.InternalMessageInfo

func (m *Volume) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Volume) GetState() VolumeState {
	if m != nil {
		return m.State
	}
	return VolumeState_NEW
}

func (m *Volume) GetShards() int64 {
	if m != nil {
		return m.Shards
	}
	return 0
}

func (m *Volume) GetRequestedShards() int64 {
	if m != nil {
		return m.RequestedShards
	}
	return 0
}

func (m *Volume) GetCurrentShards() []int64 {
	if m != nil {
		return m.CurrentShards
	}
	return nil
}

type MonitorResponseHeader struct {
	Revision             int64    `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	Error                int32    `protobuf:"varint,2,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,3,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MonitorResponseHeader) Reset()         { *m = MonitorResponseHeader{} }
func (m *MonitorResponseHeader) String() string { return proto.CompactTextString(m) }
func (*MonitorResponseHeader) ProtoMessage()    {}
func (*MonitorResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{26}
}
func (m *MonitorResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MonitorResponseHeader.Unmarshal(m, b)
}
func (m *MonitorResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MonitorResponseHeader.Marshal(b, m, deterministic)
}
func (dst *MonitorResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MonitorResponseHeader.Merge(dst, src)
}
func (m *MonitorResponseHeader) XXX_Size() int {
	return xxx_messageInfo_MonitorResponseHeader.Size(m)
}
func (m *MonitorResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_MonitorResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_MonitorResponseHeader proto.InternalMessageInfo

func (m *MonitorResponseHeader) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *MonitorResponseHeader) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

func (m *MonitorResponseHeader) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

type WatchRequestHeader struct {
	StartRevision        int64    `protobuf:"varint,1,opt,name=start_revision,json=startRevision,proto3" json:"start_revision,omitempty"`
	End                  bool     `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchRequestHeader) Reset()         { *m = WatchRequestHeader{} }
func (m *WatchRequestHeader) String() string { return proto.CompactTextString(m) }
func (*WatchRequestHeader) ProtoMessage()    {}
func (*WatchRequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{27}
}
func (m *WatchRequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchRequestHeader.Unmarshal(m, b)
}
func (m *WatchRequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchRequestHeader.Marshal(b, m, deterministic)
}
func (dst *WatchRequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchRequestHeader.Merge(dst, src)
}
func (m *WatchRequestHeader) XXX_Size() int {
	return xxx_messageInfo_WatchRequestHeader.Size(m)
}
func (m *WatchRequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchRequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_WatchRequestHeader proto.InternalMessageInfo

func (m *WatchRequestHeader) GetStartRevision() int64 {
	if m != nil {
		return m.StartRevision
	}
	return 0
}

func (m *WatchRequestHeader) GetEnd() bool {
	if m != nil {
		return m.End
	}
	return false
}

type WatchResponseHeader struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Canceled             bool     `protobuf:"varint,2,opt,name=canceled,proto3" json:"canceled,omitempty"`
	Error                bool     `protobuf:"varint,3,opt,name=error,proto3" json:"error,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,4,opt,name=error_msg,json=errorMsg,proto3" json:"error_msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WatchResponseHeader) Reset()         { *m = WatchResponseHeader{} }
func (m *WatchResponseHeader) String() string { return proto.CompactTextString(m) }
func (*WatchResponseHeader) ProtoMessage()    {}
func (*WatchResponseHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_monitor_1a8f67de4e83270d, []int{28}
}
func (m *WatchResponseHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WatchResponseHeader.Unmarshal(m, b)
}
func (m *WatchResponseHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WatchResponseHeader.Marshal(b, m, deterministic)
}
func (dst *WatchResponseHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WatchResponseHeader.Merge(dst, src)
}
func (m *WatchResponseHeader) XXX_Size() int {
	return xxx_messageInfo_WatchResponseHeader.Size(m)
}
func (m *WatchResponseHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_WatchResponseHeader.DiscardUnknown(m)
}

var xxx_messageInfo_WatchResponseHeader proto.InternalMessageInfo

func (m *WatchResponseHeader) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *WatchResponseHeader) GetCanceled() bool {
	if m != nil {
		return m.Canceled
	}
	return false
}

func (m *WatchResponseHeader) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *WatchResponseHeader) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientSettingsRequest)(nil), "api.ClientSettingsRequest")
	proto.RegisterType((*ClientSettingsResponse)(nil), "api.ClientSettingsResponse")
	proto.RegisterType((*ClientSettings)(nil), "api.ClientSettings")
	proto.RegisterType((*RabinChunkAlgorithm)(nil), "api.RabinChunkAlgorithm")
	proto.RegisterType((*FixedChunkAlgorithm)(nil), "api.FixedChunkAlgorithm")
	proto.RegisterType((*FastCDCChunkAlgorithm)(nil), "api.FastCDCChunkAlgorithm")
	proto.RegisterType((*ServerSettingsRequest)(nil), "api.ServerSettingsRequest")
	proto.RegisterType((*ServerSettingsResponse)(nil), "api.ServerSettingsResponse")
	proto.RegisterType((*ServerSettings)(nil), "api.ServerSettings")
	proto.RegisterType((*GetBlockStoresRequest)(nil), "api.GetBlockStoresRequest")
	proto.RegisterType((*GetBlockStoresResponse)(nil), "api.GetBlockStoresResponse")
	proto.RegisterType((*GetIndexStoresRequest)(nil), "api.GetIndexStoresRequest")
	proto.RegisterType((*GetIndexStoresResponse)(nil), "api.GetIndexStoresResponse")
	proto.RegisterType((*NodeReplicaSet)(nil), "api.NodeReplicaSet")
	proto.RegisterType((*Node)(nil), "api.Node")
	proto.RegisterType((*GetVolumesRequest)(nil), "api.GetVolumesRequest")
	proto.RegisterType((*GetVolumesResponse)(nil), "api.GetVolumesResponse")
	proto.RegisterType((*CreateVolumeRequest)(nil), "api.CreateVolumeRequest")
	proto.RegisterType((*CreateVolumeResponse)(nil), "api.CreateVolumeResponse")
	proto.RegisterType((*DeleteVolumeRequest)(nil), "api.DeleteVolumeRequest")
	proto.RegisterType((*DeleteVolumeResponse)(nil), "api.DeleteVolumeResponse")
	proto.RegisterType((*WatchVolumesRequest)(nil), "api.WatchVolumesRequest")
	proto.RegisterType((*WatchVolumesResponse)(nil), "api.WatchVolumesResponse")
	proto.RegisterType((*UpdateShardsRequest)(nil), "api.UpdateShardsRequest")
	proto.RegisterType((*UpdateShardsResponse)(nil), "api.UpdateShardsResponse")
	proto.RegisterType((*Volume)(nil), "api.Volume")
	proto.RegisterType((*MonitorResponseHeader)(nil), "api.MonitorResponseHeader")
	proto.RegisterType((*WatchRequestHeader)(nil), "api.WatchRequestHeader")
	proto.RegisterType((*WatchResponseHeader)(nil), "api.WatchResponseHeader")
	proto.RegisterEnum("api.HashAlgorithm", HashAlgorithm_name, HashAlgorithm_value)
	proto.RegisterEnum("api.VolumeState", VolumeState_name, VolumeState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SettingsClient is the client API for Settings service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SettingsClient interface {
	GetClientSettings(ctx context.Context, in *ClientSettingsRequest, opts ...grpc.CallOption) (*ClientSettingsResponse, error)
	GetServerSettings(ctx context.Context, in *ServerSettingsRequest, opts ...grpc.CallOption) (*ServerSettingsResponse, error)
}

type settingsClient struct {
	cc *grpc.ClientConn
}

func NewSettingsClient(cc *grpc.ClientConn) SettingsClient {
	return &settingsClient{cc}
}

func (c *settingsClient) GetClientSettings(ctx context.Context, in *ClientSettingsRequest, opts ...grpc.CallOption) (*ClientSettingsResponse, error) {
	out := new(ClientSettingsResponse)
	err := c.cc.Invoke(ctx, "/api.Settings/GetClientSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsClient) GetServerSettings(ctx context.Context, in *ServerSettingsRequest, opts ...grpc.CallOption) (*ServerSettingsResponse, error) {
	out := new(ServerSettingsResponse)
	err := c.cc.Invoke(ctx, "/api.Settings/GetServerSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsServer is the server API for Settings service.
type SettingsServer interface {
	GetClientSettings(context.Context, *ClientSettingsRequest) (*ClientSettingsResponse, error)
	GetServerSettings(context.Context, *ServerSettingsRequest) (*ServerSettingsResponse, error)
}

func RegisterSettingsServer(s *grpc.Server, srv SettingsServer) {
	s.RegisterService(&_Settings_serviceDesc, srv)
}

func _Settings_GetClientSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetClientSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Settings/GetClientSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetClientSettings(ctx, req.(*ClientSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Settings_GetServerSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsServer).GetServerSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Settings/GetServerSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsServer).GetServerSettings(ctx, req.(*ServerSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Settings_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Settings",
	HandlerType: (*SettingsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientSettings",
			Handler:    _Settings_GetClientSettings_Handler,
		},
		{
			MethodName: "GetServerSettings",
			Handler:    _Settings_GetServerSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}

// NodesClient is the client API for Nodes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodesClient interface {
	GetBlockStores(ctx context.Context, in *GetBlockStoresRequest, opts ...grpc.CallOption) (*GetBlockStoresResponse, error)
	GetIndexStores(ctx context.Context, in *GetIndexStoresRequest, opts ...grpc.CallOption) (*GetIndexStoresResponse, error)
}

type nodesClient struct {
	cc *grpc.ClientConn
}

func NewNodesClient(cc *grpc.ClientConn) NodesClient {
	return &nodesClient{cc}
}

func (c *nodesClient) GetBlockStores(ctx context.Context, in *GetBlockStoresRequest, opts ...grpc.CallOption) (*GetBlockStoresResponse, error) {
	out := new(GetBlockStoresResponse)
	err := c.cc.Invoke(ctx, "/api.Nodes/GetBlockStores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodesClient) GetIndexStores(ctx context.Context, in *GetIndexStoresRequest, opts ...grpc.CallOption) (*GetIndexStoresResponse, error) {
	out := new(GetIndexStoresResponse)
	err := c.cc.Invoke(ctx, "/api.Nodes/GetIndexStores", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodesServer is the server API for Nodes service.
type NodesServer interface {
	GetBlockStores(context.Context, *GetBlockStoresRequest) (*GetBlockStoresResponse, error)
	GetIndexStores(context.Context, *GetIndexStoresRequest) (*GetIndexStoresResponse, error)
}

func RegisterNodesServer(s *grpc.Server, srv NodesServer) {
	s.RegisterService(&_Nodes_serviceDesc, srv)
}

func _Nodes_GetBlockStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).GetBlockStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Nodes/GetBlockStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).GetBlockStores(ctx, req.(*GetBlockStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodes_GetIndexStores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodesServer).GetIndexStores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Nodes/GetIndexStores",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodesServer).GetIndexStores(ctx, req.(*GetIndexStoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nodes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Nodes",
	HandlerType: (*NodesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBlockStores",
			Handler:    _Nodes_GetBlockStores_Handler,
		},
		{
			MethodName: "GetIndexStores",
			Handler:    _Nodes_GetIndexStores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitor.proto",
}

// VolumesClient is the client API for Volumes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VolumesClient interface {
	Get(ctx context.Context, in *GetVolumesRequest, opts ...grpc.CallOption) (*GetVolumesResponse, error)
	Create(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	Delete(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	Watch(ctx context.Context, opts ...grpc.CallOption) (Volumes_WatchClient, error)
	UpdateShards(ctx context.Context, in *UpdateShardsRequest, opts ...grpc.CallOption) (*UpdateShardsResponse, error)
}

type volumesClient struct {
	cc *grpc.ClientConn
}

func NewVolumesClient(cc *grpc.ClientConn) VolumesClient {
	return &volumesClient{cc}
}

func (c *volumesClient) Get(ctx context.Context, in *GetVolumesRequest, opts ...grpc.CallOption) (*GetVolumesResponse, error) {
	out := new(GetVolumesResponse)
	err := c.cc.Invoke(ctx, "/api.Volumes/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumesClient) Create(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, "/api.Volumes/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumesClient) Delete(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, "/api.Volumes/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumesClient) Watch(ctx context.Context, opts ...grpc.CallOption) (Volumes_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Volumes_serviceDesc.Streams[0], "/api.Volumes/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &volumesWatchClient{stream}
	return x, nil
}

type Volumes_WatchClient interface {
	Send(*WatchVolumesRequest) error
	Recv() (*WatchVolumesResponse, error)
	grpc.ClientStream
}

type volumesWatchClient struct {
	grpc.ClientStream
}

func (x *volumesWatchClient) Send(m *WatchVolumesRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *volumesWatchClient) Recv() (*WatchVolumesResponse, error) {
	m := new(WatchVolumesResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *volumesClient) UpdateShards(ctx context.Context, in *UpdateShardsRequest, opts ...grpc.CallOption) (*UpdateShardsResponse, error) {
	out := new(UpdateShardsResponse)
	err := c.cc.Invoke(ctx, "/api.Volumes/UpdateShards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VolumesServer is the server API for Volumes service.
type VolumesServer interface {
	Get(context.Context, *GetVolumesRequest) (*GetVolumesResponse, error)
	Create(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	Delete(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	Watch(Volumes_WatchServer) error
	UpdateShards(context.Context, *UpdateShardsRequest) (*UpdateShardsResponse, error)
}

func RegisterVolumesServer(s *grpc.Server, srv VolumesServer) {
	s.RegisterService(&_Volumes_serviceDesc, srv)
}

func _Volumes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Volumes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumesServer).Get(ctx, req.(*GetVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volumes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Volumes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumesServer).Create(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volumes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Volumes/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumesServer).Delete(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Volumes_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(VolumesServer).Watch(&volumesWatchServer{stream})
}

type Volumes_WatchServer interface {
	Send(*WatchVolumesResponse) error
	Recv() (*WatchVolumesRequest, error)
	grpc.ServerStream
}

type volumesWatchServer struct {
	grpc.ServerStream
}

func (x *volumesWatchServer) Send(m *WatchVolumesResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *volumesWatchServer) Recv() (*WatchVolumesRequest, error) {
	m := new(WatchVolumesRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Volumes_UpdateShards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateShardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumesServer).UpdateShards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Volumes/UpdateShards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumesServer).UpdateShards(ctx, req.(*UpdateShardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Volumes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Volumes",
	HandlerType: (*VolumesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Volumes_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Volumes_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Volumes_Delete_Handler,
		},
		{
			MethodName: "UpdateShards",
			Handler:    _Volumes_UpdateShards_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Volumes_Watch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "monitor.proto",
}

func init() { proto.RegisterFile("monitor.proto", fileDescriptor_monitor_1a8f67de4e83270d) }

var fileDescriptor_monitor_1a8f67de4e83270d = []byte{
	// 1159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x57, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0xf7, 0x7a, 0xfd, 0x79, 0x1c, 0xbb, 0xfe, 0x8f, 0x9b, 0xc4, 0x75, 0xf5, 0x57, 0x61, 0xa5,
	0xa2, 0xa4, 0x17, 0x49, 0x70, 0x45, 0x84, 0xc4, 0x05, 0x4a, 0x6c, 0x27, 0x0e, 0xd4, 0x16, 0x1a,
	0x37, 0x54, 0xe2, 0xc6, 0x9a, 0x7a, 0x27, 0xf6, 0xaa, 0xfb, 0x61, 0x76, 0x27, 0x26, 0xad, 0x04,
	0xe2, 0x0d, 0x78, 0x06, 0x6e, 0xb9, 0xe0, 0x59, 0x78, 0x24, 0x34, 0x1f, 0xbb, 0xde, 0xdd, 0x8c,
	0x10, 0x22, 0x82, 0xbb, 0x3d, 0x5f, 0xbf, 0x73, 0x7e, 0x67, 0x8e, 0xe7, 0x8c, 0xa1, 0xe9, 0x05,
	0xbe, 0xc3, 0x82, 0xf0, 0x68, 0x1d, 0x06, 0x2c, 0x40, 0x26, 0x59, 0x3b, 0xd6, 0x3e, 0xec, 0x0e,
	0x5c, 0x87, 0xfa, 0x6c, 0x46, 0x19, 0x73, 0xfc, 0x65, 0x84, 0xe9, 0xf7, 0xb7, 0x34, 0x62, 0xd6,
	0x8f, 0xb0, 0x97, 0x37, 0x44, 0xeb, 0xc0, 0x8f, 0x28, 0xea, 0x43, 0x65, 0x45, 0x89, 0x4d, 0xc3,
	0xae, 0xf1, 0x91, 0x71, 0xd0, 0xe8, 0xf7, 0x8e, 0xc8, 0xda, 0x39, 0x9a, 0x48, 0xec, 0xd8, 0x6b,
	0x2c, 0x3c, 0xb0, 0xf2, 0x44, 0xc7, 0x50, 0x8b, 0x14, 0x4e, 0xb7, 0x28, 0xa2, 0x3a, 0x22, 0x2a,
	0x97, 0x22, 0x71, 0xb2, 0x7e, 0x29, 0x42, 0x2b, 0x6b, 0x44, 0x16, 0x34, 0x3d, 0xc7, 0x9f, 0xdf,
	0x38, 0xae, 0x3b, 0x8f, 0x9c, 0x0f, 0x54, 0xa4, 0x2f, 0xe3, 0x86, 0xe7, 0xf8, 0x17, 0x8e, 0xeb,
	0xce, 0x9c, 0x0f, 0x14, 0x1d, 0x43, 0x7d, 0x45, 0xa2, 0xd5, 0x9c, 0xb8, 0xcb, 0x40, 0x24, 0x6a,
	0xf5, 0x91, 0x48, 0x34, 0x26, 0xd1, 0xea, 0xcc, 0x5d, 0x06, 0xa1, 0xc3, 0x56, 0x1e, 0xae, 0xad,
	0x94, 0x88, 0x4e, 0xa0, 0x1c, 0x92, 0xb7, 0x8e, 0xdf, 0x35, 0x45, 0x55, 0x5d, 0xe1, 0x8c, 0xb9,
	0x66, 0xb0, 0xba, 0xf5, 0xdf, 0x25, 0x21, 0xe3, 0x02, 0x96, 0x8e, 0x3c, 0xe2, 0xc6, 0xb9, 0xa3,
	0x76, 0xb7, 0x94, 0x8a, 0xb8, 0xe0, 0x9a, 0xfb, 0x11, 0xc2, 0x11, 0x9d, 0x42, 0xf5, 0x86, 0x44,
	0x6c, 0x61, 0x2f, 0xba, 0xe5, 0x54, 0xc7, 0x2e, 0x48, 0xc4, 0x06, 0xc3, 0xc1, 0xbd, 0xa8, 0xd8,
	0xf9, 0x7c, 0x07, 0x60, 0xc1, 0x8d, 0x82, 0x8d, 0x35, 0x87, 0x8e, 0xa6, 0x2e, 0x84, 0xa0, 0xb4,
	0x0e, 0xdc, 0xf7, 0xa2, 0x19, 0x25, 0x2c, 0xbe, 0xd1, 0x13, 0xa8, 0x79, 0xe4, 0x4e, 0x36, 0xa9,
	0x28, 0x9a, 0x54, 0xf5, 0xc8, 0x9d, 0x68, 0x10, 0x37, 0x39, 0xbe, 0x34, 0x99, 0xca, 0xe4, 0xf8,
	0xdc, 0x64, 0x9d, 0x40, 0x47, 0x43, 0x23, 0x03, 0x66, 0x64, 0xc0, 0xac, 0x15, 0xec, 0x6a, 0x49,
	0xfc, 0x45, 0x4c, 0xa6, 0x80, 0x62, 0xa6, 0x00, 0x6e, 0x22, 0x9b, 0x65, 0xa6, 0x36, 0xb2, 0x59,
	0x8a, 0x4c, 0xfb, 0xb0, 0x3b, 0xa3, 0xe1, 0x86, 0x86, 0x9a, 0x31, 0xcd, 0x1b, 0xfe, 0x85, 0x31,
	0xcd, 0xa5, 0xd8, 0x8e, 0xe9, 0x31, 0xb4, 0xb2, 0x36, 0xf4, 0x7f, 0x80, 0x68, 0x45, 0x42, 0x7b,
	0x4b, 0xde, 0xc4, 0x75, 0xa1, 0x89, 0x89, 0x5c, 0x52, 0x76, 0xee, 0x06, 0x8b, 0x77, 0x33, 0x16,
	0x84, 0x34, 0x21, 0xf2, 0x03, 0xec, 0xe5, 0x0d, 0x0f, 0x20, 0x72, 0x08, 0x65, 0x3f, 0xb0, 0x29,
	0x67, 0x61, 0x26, 0x2c, 0xa6, 0x81, 0x4d, 0x31, 0x5d, 0xbb, 0xce, 0x82, 0xcc, 0x28, 0xc3, 0xd2,
	0x43, 0x55, 0x74, 0xe5, 0xdb, 0xf4, 0x4e, 0x57, 0x51, 0xc6, 0xf0, 0xdf, 0x54, 0x34, 0x82, 0x56,
	0xd6, 0xc0, 0x87, 0x3c, 0x72, 0x03, 0xa6, 0xda, 0x29, 0xbe, 0xd1, 0xb3, 0x2c, 0x60, 0x7d, 0x0b,
	0xa8, 0x60, 0xa6, 0x50, 0xe2, 0x22, 0xea, 0x42, 0x95, 0xd8, 0x76, 0x48, 0xa3, 0x48, 0xc4, 0xd7,
	0x71, 0x2c, 0x72, 0x58, 0x9f, 0x78, 0x72, 0x0e, 0xeb, 0x58, 0x7c, 0x73, 0xef, 0x75, 0xe8, 0x78,
	0x24, 0x7c, 0x2f, 0x66, 0xb0, 0x86, 0x63, 0xd1, 0xea, 0xc0, 0xff, 0x2e, 0x29, 0xfb, 0x36, 0x70,
	0x6f, 0xbd, 0x6d, 0x93, 0x02, 0x40, 0x69, 0xe5, 0x03, 0x1a, 0xf4, 0x1c, 0xaa, 0x1b, 0x09, 0xa3,
	0x18, 0x35, 0x44, 0x90, 0x84, 0xc6, 0xb1, 0xcd, 0x3a, 0x83, 0xce, 0x20, 0xa4, 0x84, 0x51, 0x65,
	0x90, 0x75, 0x24, 0x54, 0x8c, 0x14, 0x95, 0x3d, 0xa8, 0x88, 0xc1, 0x93, 0xb3, 0x6c, 0x62, 0x25,
	0x59, 0x5f, 0xc1, 0xe3, 0x2c, 0xc4, 0x3f, 0xaf, 0xda, 0x3a, 0x84, 0xce, 0x90, 0xba, 0xf4, 0x6f,
	0x94, 0xc3, 0xd3, 0x66, 0x5d, 0x1f, 0x90, 0xf6, 0x02, 0x3a, 0x6f, 0x08, 0x5b, 0xac, 0xb2, 0xa7,
	0x81, 0x8e, 0x73, 0x50, 0xfb, 0x02, 0x4a, 0x78, 0x2a, 0x97, 0x1c, 0x4e, 0x00, 0x8f, 0xb3, 0x38,
	0xaa, 0xa6, 0x93, 0x1c, 0x50, 0x37, 0x0d, 0xf4, 0x90, 0xe3, 0xfb, 0xd9, 0x80, 0xce, 0xf5, 0xda,
	0x26, 0x8c, 0xce, 0xc4, 0x61, 0xc4, 0x95, 0x3f, 0x83, 0x86, 0x74, 0x99, 0xa7, 0xfa, 0x06, 0x52,
	0x35, 0xe5, 0x87, 0xf9, 0x31, 0xec, 0x10, 0xdb, 0xa6, 0xf6, 0x3c, 0x39, 0x52, 0xf3, 0xc0, 0xc4,
	0x0d, 0xa1, 0x93, 0x50, 0xe8, 0x39, 0xb4, 0x42, 0xea, 0x05, 0x9b, 0xad, 0x93, 0x29, 0x9c, 0x9a,
	0x4a, 0x3b, 0x4b, 0x8e, 0x3f, 0x5b, 0xc1, 0x03, 0xce, 0xe1, 0x77, 0x03, 0x2a, 0x92, 0xa2, 0x76,
	0x02, 0x3f, 0x81, 0x72, 0xc4, 0x08, 0xa3, 0x6a, 0x15, 0xb7, 0x53, 0x2d, 0x99, 0x71, 0x3d, 0x96,
	0xe6, 0xd4, 0xa4, 0x9a, 0xe9, 0x49, 0x45, 0x87, 0xd0, 0x0e, 0x65, 0x83, 0xb6, 0x9c, 0x4a, 0xc2,
	0xe3, 0x51, 0xa2, 0xdf, 0x92, 0x5f, 0xdc, 0x86, 0x21, 0xf5, 0x59, 0xec, 0x58, 0x96, 0xe4, 0x95,
	0x56, 0x91, 0xbf, 0x81, 0x5d, 0x2d, 0x23, 0xd4, 0x83, 0x5a, 0x48, 0x37, 0x4e, 0xe4, 0x04, 0xbe,
	0xba, 0x66, 0x12, 0x19, 0x3d, 0x86, 0x32, 0x0d, 0xc3, 0x20, 0x54, 0x0b, 0x4b, 0x0a, 0xe8, 0x29,
	0xd4, 0xc5, 0xc7, 0xdc, 0x8b, 0x96, 0xa2, 0xee, 0x3a, 0xae, 0x09, 0xc5, 0x24, 0x5a, 0x5a, 0x13,
	0x40, 0xf7, 0xc7, 0x8e, 0x17, 0x19, 0x31, 0x12, 0xb2, 0x79, 0x2e, 0x55, 0x53, 0x68, 0x71, 0x9c,
	0xaf, 0x0d, 0x26, 0xf5, 0x6d, 0x91, 0xad, 0x86, 0xf9, 0xa7, 0xf5, 0x93, 0x9a, 0xf7, 0x5c, 0xd1,
	0x5d, 0xa8, 0x2e, 0xc4, 0x2f, 0xd9, 0x16, 0x40, 0x35, 0x1c, 0x8b, 0x9c, 0xce, 0x82, 0xf8, 0x0b,
	0xea, 0xd2, 0x18, 0x27, 0x91, 0xb7, 0x74, 0xe4, 0x05, 0xa7, 0xa3, 0x53, 0xca, 0xd2, 0x79, 0xf1,
	0x05, 0x34, 0x33, 0x2f, 0x28, 0x04, 0x50, 0x99, 0x8d, 0xcf, 0xfa, 0x9f, 0x9d, 0xb6, 0x0b, 0xe8,
	0x11, 0x34, 0x26, 0xd7, 0x78, 0x72, 0x8d, 0xc7, 0x67, 0xb3, 0xf1, 0xcb, 0xb6, 0x81, 0x9a, 0x50,
	0xc7, 0x57, 0xdf, 0x8c, 0x26, 0xc3, 0x4f, 0x4f, 0x4f, 0xda, 0xc5, 0x17, 0xaf, 0xa0, 0x91, 0x3a,
	0x73, 0x54, 0x05, 0x73, 0x3a, 0x7a, 0xd3, 0x2e, 0xa0, 0x06, 0x54, 0x07, 0x78, 0x74, 0xf6, 0x7a,
	0x34, 0x6c, 0x1b, 0x68, 0x07, 0x6a, 0x78, 0x34, 0xbb, 0xfa, 0xee, 0x6a, 0x7a, 0xd9, 0x2e, 0x72,
	0x69, 0x38, 0x7a, 0x35, 0x7a, 0xcd, 0x25, 0x93, 0x3b, 0x0a, 0x69, 0x34, 0x6c, 0x97, 0xfa, 0xbf,
	0x19, 0x50, 0x4b, 0xb6, 0xed, 0x54, 0xdc, 0xc9, 0xb9, 0x87, 0x62, 0x4f, 0xf7, 0xb4, 0x94, 0xe7,
	0xd0, 0x7b, 0xaa, 0xb5, 0xc9, 0xa6, 0x5a, 0x05, 0x85, 0x97, 0x5b, 0xe9, 0x3d, 0xdd, 0x1b, 0x20,
	0x83, 0xa7, 0x7f, 0x82, 0x58, 0x85, 0xfe, 0xaf, 0x06, 0x94, 0xf9, 0x12, 0x8a, 0xd0, 0xd7, 0xd0,
	0xca, 0xee, 0x77, 0x05, 0xab, 0x7d, 0x0d, 0x28, 0x58, 0xfd, 0x83, 0xc0, 0x2a, 0x28, 0xb0, 0xd4,
	0x6a, 0xde, 0x82, 0xdd, 0x5f, 0xe4, 0x5b, 0x30, 0xcd, 0x2e, 0xb7, 0x0a, 0xfd, 0x3f, 0x8a, 0x50,
	0x55, 0xf7, 0x1f, 0xfa, 0x1c, 0xcc, 0x4b, 0xca, 0xd0, 0x5e, 0x1c, 0x91, 0xbd, 0x5f, 0x7b, 0xfb,
	0xf7, 0xf4, 0x49, 0x49, 0x5f, 0x42, 0x45, 0x2e, 0x15, 0x24, 0xef, 0x4a, 0xcd, 0x92, 0xea, 0x3d,
	0xd1, 0x58, 0xd2, 0x00, 0x72, 0x3d, 0x28, 0x00, 0xcd, 0x5a, 0x51, 0x00, 0xba, 0x2d, 0x62, 0x15,
	0xd0, 0x39, 0x94, 0xc5, 0x6f, 0x04, 0xa5, 0x2e, 0xeb, 0x5c, 0xfd, 0x4f, 0x34, 0x96, 0x38, 0xfe,
	0xc0, 0x38, 0x31, 0xd0, 0x08, 0x76, 0xd2, 0x77, 0xa3, 0x82, 0xd2, 0x5c, 0xd8, 0x0a, 0x4a, 0x77,
	0x91, 0x5a, 0x85, 0xb7, 0x15, 0xf1, 0x0f, 0xeb, 0xe5, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2,
	0xca, 0xdb, 0xc8, 0x72, 0x0d, 0x00, 0x00,
}
